//
//  RockPaperScissorsInteractor.swift
//  SimpleIOSGames
//
//  Created by Mike I on 22.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RockPaperScissorsBusinessLogic
{
    func appendRPSResult(request: RockPaperScissors.AppendRPSResult.Request)
}

protocol RockPaperScissorsDataStore
{
    var rpsResult: RPSRoundResult? { get }
}

class RockPaperScissorsInteractor: RockPaperScissorsBusinessLogic, RockPaperScissorsDataStore
{
  var presenter: RockPaperScissorsPresentationLogic?
  var worker: RockPaperScissorsWorker?
  var rpsResult: RPSRoundResult?
  func appendRPSResult(request: RockPaperScissors.AppendRPSResult.Request)
    {
        rpsResult = worker?.appendRPSResult(round: request.round)
        if let rpsResult = rpsResult {
            let response = RockPaperScissors.AppendRPSResult.Response(rpsResult: rpsResult)
            presenter?.presentNewRPSResult(response: response)
        }
    }
}
