//
//  RockPaperScissorsPresenter.swift
//  SimpleIOSGames
//
//  Created by Mike I on 22.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RockPaperScissorsPresentationLogic
{
    func presentNewRPSResult(response: RockPaperScissors.AppendRPSResult.Response)
}

class RockPaperScissorsPresenter: RockPaperScissorsPresentationLogic
{
    weak var viewController: RockPaperScissorsDisplayLogic?
    
    func presentNewRPSResult(response: RockPaperScissors.AppendRPSResult.Response)
    {
        let viewModel = RockPaperScissors.AppendRPSResult.ViewModel(rpsResult: response.rpsResult)
        viewController?.displayNewRPSResult(viewModel: viewModel)
    }
}
