//
//  HistoryPresenter.swift
//  SimpleIOSGames
//
//  Created by Mike I on 03.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic
{
    func presentListDiceResults(response: History.GetListDiceResult.Response)
    func presentListRPSResults(response: History.GetListRPSResult.Response)
    func presentBestDiceResults(response: History.GetBestDiceResult.Response)
    func presentBestRPSResults(response: History.GetBestRPSResults.Response)
}

class HistoryPresenter: HistoryPresentationLogic
{
    weak var viewController: HistoryDisplayLogic?
    
    func presentListDiceResults(response: History.GetListDiceResult.Response)
    {
        let viewModel = History.GetListDiceResult.ViewModel(diceResults: response.diceResults)
        viewController?.displayDiceResults(viewModel: viewModel)
    }
    func presentListRPSResults(response: History.GetListRPSResult.Response)
    {
        let viewModel = History.GetListRPSResult.ViewModel(rpsResults: response.rpsResults)
        viewController?.displayRPSResults(viewModel: viewModel)
    }
    func presentBestDiceResults(response: History.GetBestDiceResult.Response)
    {
        let viewModel = History.GetBestDiceResult.ViewModel(diceResults: response.diceResults)
        viewController?.displayBestDiceResults(viewModel: viewModel)
    }
    func presentBestRPSResults(response: History.GetBestRPSResults.Response)
    {
        let viewModel = History.GetBestRPSResults.ViewModel(rpsResults: response.rpsResults)
        viewController?.displayBestRPSResults(viewModel: viewModel)
    }
}
