//
//  HistoryRouter.swift
//  SimpleIOSGames
//
//  Created by Mike I on 03.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit



protocol HistoryDataPassing
{
    var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: HistoryDataPassing
{
    weak var viewController: HistoryViewController?
    var dataStore: HistoryDataStore?
    
}
