//
//  HistoryModels.swift
//  SimpleIOSGames
//
//  Created by Mike I on 03.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum History
{
    
    enum AppendDiceResult
    {
        struct Request
        {
            var imageUrl: String
        }
        struct Response
        {
            var diceResult:DiceResult
        }
        struct ViewModel
        {
            var diceResult:DiceResult
        }
    }
    enum GetListDiceResult
    {
        struct Request
        {
        }
        struct Response
        {
            var diceResults:[DiceResult]
        }
        struct ViewModel
        {
            var diceResults:[DiceResult]
        }
    }
    enum AppendRPSResult
    {
        struct Request
        {
            var round: RPSRound
        }
        struct Response
        {
            var rpsResult:RPSRoundResult
        }
        struct ViewModel
        {
            var rpsResult:RPSRoundResult
        }
    }
    enum GetListRPSResult
    {
        struct Request
        {
        }
        struct Response
        {
            var rpsResults:[RPSRoundResult]
        }
        struct ViewModel
        {
            var rpsResults:[RPSRoundResult]
        }
    }
    enum GetBestRPSResults
    {
        struct Request
        {
        }
        struct Response
        {
            var rpsResults:RPSRoundResult?
        }
        struct ViewModel
        {
            var rpsResults:RPSRoundResult?
        }
    }
    enum GetBestDiceResult
    {
        struct Request
        {
        }
        struct Response
        {
            var diceResults:[(DiceResult, Float)]?
        }
        struct ViewModel
        {
            var diceResults:[(DiceResult, Float)]?
        }
    }
}
