//
//  DiceGameInteractor.swift
//  SimpleIOSGames
//
//  Created by Mike I on 22.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiceGameBusinessLogic
{
    func appendDiceResult(request: DiceGame.AppendDiceResult.Request)
}

protocol DiceGameDataStore
{
    var diceResult: DiceResult? { get }
}

class DiceGameInteractor: DiceGameBusinessLogic, DiceGameDataStore
{
    var diceResult: DiceResult?
    var presenter: DiceGamePresentationLogic?
    var worker: DiceGameWorker? = DiceGameWorker(dataStore: DataStore())
    
    func appendDiceResult(request: DiceGame.AppendDiceResult.Request) {
        diceResult = worker?.appendDiceResult(imageUrl: request.imageUrl)
        if let diceResult = diceResult {
            let response = DiceGame.AppendDiceResult.Response(diceResult: diceResult)
            presenter?.presentNewDiceResult(response: response)
        }
    }
}
