//
//  DiceGamePresenter.swift
//  SimpleIOSGames
//
//  Created by Mike I on 22.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiceGamePresentationLogic
{
    func presentNewDiceResult(response: DiceGame.AppendDiceResult.Response)
}

class DiceGamePresenter: DiceGamePresentationLogic
{
    weak var viewController: DiceGameDisplayLogic?
    
    func presentNewDiceResult(response: DiceGame.AppendDiceResult.Response)
    {
        let viewModel = DiceGame.AppendDiceResult.ViewModel(diceResult: response.diceResult)
        viewController?.displayNewDiceResult(viewModel: viewModel)
    }
}
