//
//  DiceGameModels.swift
//  SimpleIOSGames
//
//  Created by Mike I on 22.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DiceGame
{
  // MARK: Use cases
  
    enum AppendDiceResult
    {
        struct Request
        {
            var imageUrl: String
        }
        struct Response
        {
            var diceResult:DiceResult
        }
        struct ViewModel
        {
            var diceResult:DiceResult
        }
    }
}
